# Generated by Django 5.2.2 on 2026-06-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productorder_cancel_token_alter_contactmessage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('honey', 'Honey'), ('animals', 'Animals'), ('pickles', 'Pickles')], max_length=50)),
                ('description', models.TextField()),
                ('detail_description', models.TextField(blank=True)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('farming_method', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('main_image', models.CharField(blank=True, max_length=200)),
                ('image2', models.CharField(blank=True, max_length=200)),
                ('image3', models.CharField(blank=True, max_length=200)),
                ('image4', models.CharField(blank=True, max_length=200)),
                ('whatsapp_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
