# Generated by Django 5.2.2 on 2026-06-30 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Mango Mania Sale"', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Short tagline shown on badge/banner', max_length=300)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('combo', 'Combo Deal')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='e.g. 20 for 20% off, or 50 for Rs.50 off', max_digits=10)),
                ('combo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Only for combo deals - total bundle price', max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('banner_image', models.CharField(blank=True, help_text='Optional banner image path', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Apply to all products in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='shop.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Leave empty if applying to whole category', related_name='offers', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
