# Generated by Django 5.2.2 on 2026-07-02 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. DASHAIN25 — will be stored uppercase', max_length=30, unique=True)),
                ('festival_name', models.CharField(blank=True, help_text='e.g. Dashain, Tihar, Holi', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Shown next to the coupon code on the offers page', max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='e.g. 25 for 25% off, or 200 for Rs.200 off', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on discount for percentage coupons (optional)', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart subtotal required to use this coupon', max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Amount of this product in the bundle. E.g. 1.9 for 1.9 kg chicken, 3 for 3 pieces of lemon.', max_digits=6)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='shop.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
