# Generated by Django 5.2.2 on 2026-08-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_wishlist_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Automatically unchecked when the subscriber clicks the unsubscribe link in an email.'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
