# Generated by Django 5.2.2 on 2026-09-07 04:56

import shop.imagekit_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_newslettersubscriber_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner image', storage=shop.imagekit_storage.ImageKitStorage(), upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, storage=shop.imagekit_storage.ImageKitStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, storage=shop.imagekit_storage.ImageKitStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, storage=shop.imagekit_storage.ImageKitStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, storage=shop.imagekit_storage.ImageKitStorage(), upload_to='products/'),
        ),
    ]
