# Generated by Django 5.2.2 on 2026-09-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_offer_banner_image_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('harvest', 'Harvest — new stock in from the farm'), ('sale', 'Sale — stock out, sold (website order or shop POS)'), ('waste', 'Waste — spoiled/bad stock, not sellable'), ('return', 'Return — stock back in, e.g. a cancelled order'), ('adjustment_add', 'Adjustment (add) — stock count found higher than recorded'), ('adjustment_remove', 'Adjustment (remove) — stock count found lower than recorded')], max_length=20)),
                ('source', models.CharField(choices=[('admin', 'Entered manually in Django admin'), ('abms', 'Pushed from ABMS (farm app)'), ('website', 'Website order'), ('pos', 'Shop POS')], default='admin', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Always a POSITIVE number, in the product's own unit. The movement type above decides whether it adds to or removes from stock — you never need to enter a minus sign.", max_digits=8)),
                ('note', models.CharField(blank=True, help_text='e.g. "rain damage", "sold to walk-in customer at farm shop"', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='shop.product')),
                ('related_order', models.ForeignKey(blank=True, help_text='Only set for "sale"/"return" movements that came from a website order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='shop.productorder')),
                ('variant', models.ForeignKey(blank=True, help_text='Only used for "Fixed weight" products (goat/chicken) — which specific animal this movement is about. Left blank for every other pricing mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='shop.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
