# Generated by Django 5.2.2 on 2026-09-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_inventorymovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('farm', 'Grown/Raised on our farm'), ('sourced', 'Sourced from other Nepali producers')], default='farm', help_text='Controls the "Our Farm" / "Sourced in Nepal" label shown on the shop and product pages. Defaults to farm-grown — flip individual products (e.g. Apple, Kiwi) to "sourced" if they aren\'t actually grown here.', max_length=10),
        ),
    ]
