# Generated by Django 5.2.2 on 2026-09-16 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='For packaged goods only (jars, bottles). Scan a blank label with your barcode scanner into this field once, print that same code onto your product label, and the POS will recognize it at checkout. Leave blank for anything sold by weight/variant.', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('cart_snapshot', models.JSONField(help_text='Same shape as ProductOrder.cart_snapshot: [{product_id, weight, qty, variant_id}, ...]')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='related_pos_sale',
            field=models.ForeignKey(blank=True, help_text='Only set for "sale" movements that came from the shop POS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='shop.possale'),
        ),
    ]
