# Generated by Django 5.2.2 on 2026-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_barcode_possale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='client_sale_id',
            field=models.CharField(blank=True, help_text='A UUID generated on the POS device itself, before the sale is ever sent to the server. If the same ID arrives twice — a double-tap on Complete Sale, a retried request after a dropped connection, or a queued offline sale being synced — the second attempt returns the original result instead of creating a second sale. Null only for sales that predate this field.', max_length=64, null=True, unique=True),
        ),
    ]
