# Generated by Django 5.2.2 on 2026-09-29 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_userprofile_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vat_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='possale',
            name='exempt_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='possale',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='possale',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='VAT scaffolding — dormant until BusinessSettings.is_vat_enabled is switched on. Most of this catalog (fresh produce, live animals, milk, eggs) is VAT-exempt under Nepali law; only check this for a processed/packaged item once VAT registration actually happens.'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit (उधारो)'), ('split', 'Split Payment')], help_text="Derived, not user-entered: the sale's one payment method, or 'split' when it has more than one payment line. See the payments related set for the actual breakdown.", max_length=20),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive — transaction_type decides the direction.', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit_sale', 'Credit Sale'), ('repayment', 'Repayment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(help_text="The staff member who actually took this payment/recorded this sale — the PIN-unlock 'current operator', not necessarily whoever the terminal is logged in as.", on_delete=django.db.models.deletion.PROTECT, related_name='recorded_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('related_pos_sale', models.ForeignKey(blank=True, help_text='Set for credit_sale rows; left blank for a standalone repayment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='shop.possale')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='shop.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='possale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Only set when at least one payment line on this sale is credit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='shop.customer'),
        ),
        migrations.CreateModel(
            name='POSSalePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit (उधारो)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.possale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
