# Generated by Django 5.2.2 on 2026-09-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_backfill_possale_exempt_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff_number',
            field=models.CharField(blank=True, help_text='Shown on the POS header once this person unlocks (e.g. "NIKESH 001") — deliberately separate from both the PIN and the DB id, since neither of those should ever be displayed on screen. Set once per staff member.', max_length=10),
        ),
    ]
