# Generated by Django 5.2.2 on 2026-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_userprofile_staff_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_entry_mode',
            field=models.CharField(choices=[('stepper', 'Stepper — tap +/- in weight_step increments'), ('exact', 'Exact — type the scale reading in grams (e.g. 230g, or 1.150kg once over 1kg)')], default='stepper', help_text='Only used for "Variable weight" products. "Stepper" is the +/- button UI (weight_step controls the increment). "Exact" is a free-typed gram entry for produce weighed on a scale at checkout (coriander, dragon fruit, watermelon, papaya, cauliflower) — weight_step is ignored in this mode.', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_step',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Only used for "Variable weight" products in "Stepper" entry mode. The increment customers can adjust the weight by, e.g. 0.50 for fruit (500g steps), 0.25 for pickle jars.', max_digits=4),
        ),
    ]
