# Generated by Django 5.2.2 on 2026-09-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_reorganize_pos_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSellingUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kg'), ('gram', 'Gram'), ('dozen', 'Dozen'), ('liter', 'Liter'), ('milliliter', 'Milliliter'), ('crate', 'Crate')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text="This unit's own price, e.g. Rs. 20 for Piece, Rs. 550 for Crate. Entered directly, never calculated by multiplying another unit's price -- bulk units are usually discounted, not a flat multiple.", max_digits=10)),
                ('quantity_in_base_units', models.DecimalField(decimal_places=2, default=1, help_text="How many of this product's own stock-counting unit ONE of this selling unit equals -- e.g. 1 for Piece, 30 for a Crate of eggs. Only used to deduct the correct amount from inventory when this unit is sold; never used to calculate price.", max_digits=8)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected in the POS keypad modal when this product has more than one unit.')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to stop offering this unit at POS without deleting its price history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_units', to='shop.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
