# Generated by Django 5.2.2 on 2026-09-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0029_productsellingunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="possale",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                help_text="The coupon code applied to this sale, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pos_sales",
                to="shop.coupon",
            ),
        ),
        migrations.AddField(
            model_name="possale",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount knocked off the pre-tax subtotal by the coupon above. Zero when no coupon was used.",
                max_digits=10,
            ),
        ),
    ]
