# Generated by Django 5.2.2 on 2026-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_productsellingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_entry_mode',
            field=models.CharField(choices=[('stepper', 'Stepper — POS keypad starts on Kg'), ('exact', 'Exact — POS keypad starts on Gram')], default='stepper', help_text='Only used for "Variable weight" products. Both modes use the same POS keypad (a Kg/Gram unit switcher with +/- nudges) -- this only picks which unit starts selected when the modal opens. "Exact" starts on Gram, for produce typically weighed on a scale rather than bought in round step sizes (coriander, dragon fruit, watermelon, papaya, cauliflower). "Stepper" starts on Kg.', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_step',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Only used for "Variable weight" products. The POS keypad\'s +/- nudge increment while "Kg" is selected, e.g. 0.50 for fruit (500g steps), 0.25 for pickle jars.', max_digits=4),
        ),
    ]
