# Generated by Django 5.2.2 on 2026-10-01 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_weight_entry_mode_and_more'),
        ('shop', '0030_possale_coupon_possale_discount_amount'),
    ]

    operations = [
    ]
