# Generated by Django 5.2.2 on 2026-10-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_merge_20261001_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='required_total rounded to the nearest rupee, minus required_total itself -- e.g. -0.37 if a Rs. 222.37 total was rounded down to Rs. 222. Always between -0.99 and +0.99.', max_digits=4),
        ),
    ]
