# Generated by Django 5.2.2 on 2026-10-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_possale_round_off_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text="Always a POSITIVE number, in the product's own unit. The movement type above decides whether it adds to or removes from stock — you never need to enter a minus sign. 3 decimal places so a single-gram scale reading (e.g. 0.335kg from a 335g reading) can be recorded exactly, not just the nearest 10g.", max_digits=8),
        ),
    ]
