# Generated by Django 5.2.2 on 2026-10-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_inventorymovement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='When current stock drops to this level or below, the product is flagged on the POS stock-alert table and triggers a one-time Telegram notification the moment stock crosses down past this line (see shop/signals.py). Not used for "Fixed weight" products (goats/chickens) -- those are tracked per-animal, not by a stock count.'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('harvest', 'Harvest — new stock in from the farm'), ('purchase', 'Purchase — new stock bought in from an outside supplier'), ('sale', 'Sale — stock out, sold (website order or shop POS)'), ('waste', 'Waste — spoiled/bad stock, not sellable'), ('return', 'Return — stock back in, e.g. a cancelled order'), ('adjustment_add', 'Adjustment (add) — stock count found higher than recorded'), ('adjustment_remove', 'Adjustment (remove) — stock count found lower than recorded')], max_length=20),
        ),
    ]
