# Generated by Django 5.2.2 on 2026-10-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(help_text='Required -- needed to actually find a उधारो customer in person if a debt goes unpaid.'),
        ),
    ]
