# Generated by Django 5.2.2 on 2026-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleitem',
            name='reference_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For a fixed-weight bundle item: the animal weight this combo\'s advertised price assumes. Picking a variant at or below this weight costs exactly the combo price; picking a heavier one adds the real price difference. Only meaningful when the bundled product is "Fixed weight". Leave blank to auto-fill with the cheapest currently available animal\'s weight when this row is first saved -- once set (auto-filled or typed in), it stays fixed and is never recomputed as stock changes.', max_digits=6, null=True),
        ),
    ]
