# Generated by Django 5.2.2 on 2026-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_bundleitem_reference_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "FY 2083/84" or "2026 Goal" — shown on the dashboard as-is.', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Target revenue in Rs.', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text="Only active targets are ever shown on the dashboard. If more than one active target's period contains today, the dashboard prefers that one; otherwise it shows the most recently started active target.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
