# Generated by Django 5.2.2 on 2026-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_revenuetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abms_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_category', models.CharField(max_length=60)),
                ('purchase_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('life_years', models.PositiveSmallIntegerField()),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_centre', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed')], default='active', max_length=10)),
                ('disposed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abms_id', models.CharField(db_index=True, help_text="The ABMS Firestore document id (e.g. 'c_xxxxxxxx') — the idempotency key for syncing: the same id arriving twice is a no-op, never a duplicate row.", max_length=64, unique=True)),
                ('date', models.DateField(help_text='AD date of the cost, as recorded in ABMS.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive for an ordinary cost, negative for a reversal.', max_digits=12)),
                ('entry_type', models.CharField(choices=[('cost', 'Cost'), ('reversal', 'Reversal')], default='cost', max_length=10)),
                ('reversal_of', models.CharField(blank=True, help_text='abms_id of the original CostEntry this reverses. Only set when entry_type=reversal.', max_length=64)),
                ('cost_centre', models.CharField(db_index=True, help_text="e.g. 'crop:mango', 'tree:lychee', 'livestock:goat', 'livestock:chicken', 'bees', 'vermi', 'water', 'shared'.", max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('allocation_rule', models.CharField(blank=True, choices=[('equal', 'Equal split'), ('manual', 'Manual percentages')], max_length=10)),
                ('allocation_manual', models.JSONField(blank=True, help_text="{'crop:mango': 40, 'livestock:goat': 60} — only set when allocation_rule='manual'. Must sum to 100.", null=True)),
                ('entered_by_email', models.CharField(blank=True, max_length=254)),
                ('abms_created_at', models.DateTimeField(blank=True, help_text='When ABMS itself recorded this entry (its serverTimestamp).', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When this row was synced into Django.')),
            ],
            options={
                'verbose_name_plural': 'Cost entries',
                'ordering': ['-date', '-received_at'],
                'indexes': [models.Index(fields=['date'], name='shop_costen_date_074402_idx'), models.Index(fields=['cost_centre', 'date'], name='shop_costen_cost_ce_fc9104_idx')],
            },
        ),
    ]
