# Generated by Django 5.2.2 on 2026-10-07 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_farmasset_costentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Landed cost per product unit for THIS movement — only ever set for origin='sourced' products (see PurchaseBatch). Auto-filled on first save from weighted_average_cost() for sale/waste/adjustment_remove rows when not explicitly provided; a purchase row sets it explicitly (its own landed unit cost). Always null for farm-grown products — those are costed through ABMS cost centres instead.", max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='POSSaleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text="In the product's own base unit — same meaning as InventoryMovement.quantity for this line.", max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_lines', to='shop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.possale')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale_lines', to='shop.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_direct_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('landed_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('landed_unit_cost', models.DecimalField(decimal_places=4, editable=False, max_digits=12)),
                ('is_void', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_batch', to='shop.inventorymovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_batches', to='shop.product')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
    ]
