# Generated by Django 5.2.2 on 2026-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_inventorymovement_unit_cost_possaleline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='is_wholesale',
            field=models.BooleanField(db_index=True, default=False, help_text='A bulk sale to a named buyer at manually-set per-line prices -- no coupons, no automatic offers/combos. See create_pos_sale() in shop/views.py.'),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='list_line_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What this line would have cost at the normal catalogue price -- only ever set on a wholesale sale (POSSale.is_wholesale), where it can legitimately differ from line_total (the actual amount charged). Null on every retail line, since there line_total already IS the catalogue-derived price.', max_digits=12, null=True),
        ),
    ]
