# Generated by Django 5.2.2 on 2026-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_possale_is_wholesale_possaleline_list_line_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_from_website',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide from the public website and public API. Still available in the POS, admin and inventory. Use for crops sold only wholesale or at the farm.'),
        ),
    ]
