# Generated by Django 5.2.2 on 2026-10-08 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_product_hide_from_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_centre', models.CharField(db_index=True, max_length=60)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centres', to='shop.product')),
            ],
            options={
                'ordering': ['cost_centre', 'product__name'],
                'unique_together': {('cost_centre', 'product')},
            },
        ),
    ]
