# Generated by Django 5.2.2 on 2026-10-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_costcentreproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='costentry',
            name='batch_code',
            field=models.CharField(blank=True, db_index=True, help_text='CropBatch.code this cost belongs to, for season/batch costing (see shop/batch_report.py) -- blank means "unbatched" (the normal case for a monthly/shared cost with no single crop batch). Loose CharField, not a FK, same reasoning as reversal_of above.', max_length=40),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='batch_code',
            field=models.CharField(blank=True, db_index=True, help_text="CropBatch.code this movement belongs to -- only ever meaningful for movement_type='harvest' (see shop/batch_report.py). Blank means either this isn't a harvest, or it's harvest stock that predates batch tracking for this crop ('unbatched' stock, consumed first in the batch report's FIFO attribution). Loose CharField, not a CropBatch FK, same reasoning as CostEntry.reversal_of above -- ABMS is the source of truth for the code.", max_length=40),
        ),
        migrations.CreateModel(
            name='CropBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('abms_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('cost_centre', models.CharField(db_index=True, help_text="Same key format as CostCentreProduct.cost_centre, e.g. 'crop:tomato'.", max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_batches', to='shop.product')),
            ],
            options={
                'verbose_name': 'Crop batch',
                'ordering': ['-start_date', 'code'],
            },
        ),
    ]
