# Generated by Django 5.2.2 on 2026-10-09 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_costentry_batch_code_inventorymovement_batch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentreproduct',
            name='cost_centre',
            field=models.CharField(db_index=True, help_text='Slug form only, e.g. crop:bottle-gourd -- lowercase, hyphen-separated, one colon. Only enforced on save/admin-edit, not retroactively: an existing row written before this validator existed is left alone until it is next edited.', max_length=60, validators=[django.core.validators.RegexValidator(message='Must be slug form, e.g. "crop:bottle-gourd" -- lowercase letters/digits, a colon, then lowercase letters/digits with single hyphens between words. No spaces or capitals (ABMS builds these keys with slugify, which collapses any run of other characters to one hyphen).', regex='^[a-z0-9]+:[a-z0-9]+(-[a-z0-9]+)*$')]),
        ),
    ]
