from django.urls import path

from . import views

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='v1_product_list'),
    path('products/by-slug/<slug:slug>/', views.ProductDetailBySlugView.as_view(), name='v1_product_detail_by_slug'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='v1_product_detail'),
    path('categories/', views.CategoryListView.as_view(), name='v1_category_list'),
    path('inventory/movements/', views.InventoryMovementListView.as_view(), name='v1_inventory_movement_list'),
    path('costs/', views.CostEntryListView.as_view(), name='v1_cost_entry_list'),
    path('sales/', views.POSSaleView.as_view(), name='v1_sale_list_create'),
    path('pos/unlock/', views.PosUnlockView.as_view(), name='v1_pos_unlock'),
    path('pos/lock/', views.PosLockView.as_view(), name='v1_pos_lock'),
    path('pos/customers/lookup/', views.CustomerLookupView.as_view(), name='v1_pos_customer_lookup'),
    path('pos/customers/', views.CustomerListCreateView.as_view(), name='v1_pos_customer_create'),
    path('pos/credit/repay/', views.CreditRepayView.as_view(), name='v1_pos_credit_repay'),
    path('pos/coupon/validate/', views.CouponValidateView.as_view(), name='v1_pos_coupon_validate'),
    path('pos/queue/report-failed/', views.PosQueueFailureAlertView.as_view(), name='v1_pos_queue_report_failed'),
    path('pos/queue/report-dismissed/', views.PosQueueDismissedReportView.as_view(), name='v1_pos_queue_report_dismissed'),
    path('pos/offers/', views.PosOffersListView.as_view(), name='v1_pos_offers_list'),
    path('pos/stock/', views.PosStockListView.as_view(), name='v1_pos_stock_list'),
    path('pos/restock/', views.PosRestockView.as_view(), name='v1_pos_restock'),
    path('pos/products/<int:product_id>/origin/', views.PosProductOriginUpdateView.as_view(), name='v1_pos_product_origin_update'),
    path('orders/', views.OrderCreateView.as_view(), name='v1_order_create'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='v1_order_detail'),
    path('orders/<int:pk>/cancel/', views.OrderCancelView.as_view(), name='v1_order_cancel'),
    path('orders/<int:pk>/reorder/', views.OrderReorderView.as_view(), name='v1_order_reorder'),
    path('auth/signup/', views.SignupView.as_view(), name='v1_auth_signup'),
    path('auth/login/', views.LoginView.as_view(), name='v1_auth_login'),
    path('auth/logout/', views.LogoutView.as_view(), name='v1_auth_logout'),
    path('auth/password-reset/', views.PasswordResetRequestView.as_view(), name='v1_auth_password_reset'),
    path(
        'auth/password-reset-confirm/',
        views.PasswordResetConfirmView.as_view(),
        name='v1_auth_password_reset_confirm',
    ),
    path('profile/orders/', views.ProfileOrderListView.as_view(), name='v1_profile_orders'),
    path('profile/', views.ProfileUpdateView.as_view(), name='v1_profile_update'),
    path('profile/change-password/', views.ChangePasswordView.as_view(), name='v1_profile_change_password'),
    path('wishlist/', views.WishlistListView.as_view(), name='v1_wishlist_list'),
    path('wishlist/toggle/', views.WishlistToggleView.as_view(), name='v1_wishlist_toggle'),
    path('wishlist/set-variant/', views.WishlistSetVariantView.as_view(), name='v1_wishlist_set_variant'),
    path('wishlist/move-to-cart/', views.WishlistMoveToCartView.as_view(), name='v1_wishlist_move_to_cart'),
    path('coupons/', views.CouponListView.as_view(), name='v1_coupon_list'),
    path('reports/summary/', views.ReportSummaryView.as_view(), name='v1_report_summary'),
    path('reports/sales-trend/', views.ReportSalesTrendView.as_view(), name='v1_report_sales_trend'),
    path('reports/payments/', views.ReportPaymentsView.as_view(), name='v1_report_payments'),
    path('reports/products/', views.ReportProductsView.as_view(), name='v1_report_products'),
    path('reports/credit/', views.ReportCreditView.as_view(), name='v1_report_credit'),
    path('reports/inventory/', views.ReportInventoryView.as_view(), name='v1_report_inventory'),
    path('reports/orders/', views.ReportOrdersView.as_view(), name='v1_report_orders'),
    path('reports/alerts/', views.ReportAlertsView.as_view(), name='v1_report_alerts'),
    path('reports/target/', views.ReportTargetView.as_view(), name='v1_report_target'),
    path('reports/filter-options/', views.ReportFilterOptionsView.as_view(), name='v1_report_filter_options'),
    path('reports/pl/', views.ReportPLView.as_view(), name='v1_report_pl'),
]
